language: java

branches:
  only:
  - master

env:
  global:
    - EXPO_SDK_VERSION="${APP_EXPO_SDK_VERSION}"
    - TURTLE_VERSION="${TURTLE_VERSION_NEW}"
    - NODE_VERSION="12.13.1"
    - YARN_VERSION="1.21.1"

jobs:
  include:
    - stage: publish app
      env:
        - CACHE_NAME=publish YARN_CACHE_FOLDER="/home/travis/yarn_cache"
      cache:
        directories:
          - $HOME/yarn_cache
      before_install:
        - nvm install $NODE_VERSION
        - nvm use $NODE_VERSION
        - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version $YARN_VERSION
        - export PATH="$HOME/.yarn/bin:$PATH"
      install:
        - yarn global add expo-cli
      script:
        - expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD --non-interactive
        - yarn
        - expo publish
    - stage: build standalone apps
      env:
        - CACHE_NAME=build-android-v3 YARN_CACHE_FOLDER="/home/travis/yarn_cache"
      jdk: openjdk8
      cache:
        directories:
          - $HOME/.turtle
          - $HOME/yarn_cache
          - $HOME/.gradle/wrapper
      before_install:
        - nvm install $NODE_VERSION
        - nvm use $NODE_VERSION
        - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version $YARN_VERSION
        - export PATH="$HOME/.yarn/bin:$PATH"
      install:
        - yarn global add gulp-cli turtle-cli@$TURTLE_VERSION
      script:
        - yarn
        - export ARTIFACT_PATH="/home/travis/expo-project-$TRAVIS_COMMIT-`date +%s`.apk"
        - turtle setup:android --sdk-version $EXPO_SDK_VERSION > /dev/null || travis_terminate 1
        - echo $EXPO_ANDROID_KEYSTORE_BASE64 > expo-project.jks.base64
        - base64 --decode expo-project.jks.base64 > expo-project.jks
        - turtle build:android
            --keystore-path ./expo-project.jks
            --keystore-alias $EXPO_ANDROID_KEYSTORE_ALIAS
            --type apk
            -o $ARTIFACT_PATH
    - stage: build standalone apps
      env:
        - CACHE_NAME=build-android-v3 YARN_CACHE_FOLDER="/home/travis/yarn_cache"
      jdk: openjdk8
      cache:
        directories:
          - $HOME/.turtle
          - $HOME/yarn_cache
          - $HOME/.gradle/wrapper
      before_install:
        - nvm install $NODE_VERSION
        - nvm use $NODE_VERSION
        - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version $YARN_VERSION
        - export PATH="$HOME/.yarn/bin:$PATH"
      install:
        - pip install --user awscli
        - yarn global add gulp-cli turtle-cli@$TURTLE_VERSION
      script:
        - yarn
        - export ARTIFACT_PATH="/home/travis/expo-project-$TRAVIS_COMMIT-`date +%s`.aab"
        - turtle setup:android --sdk-version $EXPO_SDK_VERSION > /dev/null || travis_terminate 1
        - echo $EXPO_ANDROID_KEYSTORE_BASE64 > expo-project.jks.base64
        - base64 --decode expo-project.jks.base64 > expo-project.jks
        - turtle build:android
            --keystore-path ./expo-project.jks
            --keystore-alias $EXPO_ANDROID_KEYSTORE_ALIAS
            --type app-bundle
            -o $ARTIFACT_PATH

deploy:
  provider: releases
  api_key: "${GITHUB_API_KEY}"
  file: "*/*.apk"
  cleanup: false
  draft: true